### ISSUE TITLE
npm run generate closes prematurely.

### ISSUE THREAD

**Issue by maotora** [thebakeryio/baker#70]
When i run `npm run generate` baker opens the list to choose.

When i move to the item i need to select and press <Enter> it closes without any message or other prompts.

I tried to check the `/app/src/components` and nothing has been created.

What could be the problem?

Thank You.

**Comment by psx900910** [comment]
this problem is caused by the version of yeoman-generator package, modify `"yeoman-generator": "^0.24.1",` to `"yeoman-generator": "^0.22.0",`

**Comment by psx900910** [comment]
modify "yeoman-generator": "^0.24.1", to "yeoman-generator": "^0.22.0" in `package.json` file

**Comment by callmephilip** [comment]
@psx900910 thanks for digging into this. there have been certain API changes to yeoman generator that we did not catch. this should be fixed via #71. feel free to reopen the issue if you are still having issues with it
